### ISSUE TITLE
Error attempting to run CAR_2013_02_008.py and other 2013 analytic scripts

### ISSUE THREAD

**Issue by recoilforce** [iadgov/unfetter-analytic#22]
/vagrant/src$> spark-submit run_unfetter_analytic.py  -c CAR_2013_02_008.py -d day 1
Traceback (most recent call last):
  File "/vagrant/src/run_unfetter_analytic.py", line 174, in <module>
    mod = import_module(args.car_number)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/src/CAR_2013_02_008.py", line 13, in <module>
    from BaseCARAnalytic import BaseCARAnalytic
ImportError: No module named BaseCARAnalytic

**Comment by infosec-alchemist** [comment]
Three of the analytics, CAR_2013_02_008.py, CAR_2013_04_002.py and CAR_2014_11_002.py were using a class inheritance, BaseCARAnalytic, that had been removed during a code refactoring.  These three files were not refactors.
