### ISSUE TITLE
CAR_2016_04_003.py Syntax Error: unexpected character after line continuation character

### ISSUE THREAD

**Issue by recoilforce** [iadgov/unfetter-analytic#25]
Traceback (most recent call last):
  File "/home/tracerfire/src/run_unfetter_analytic.py", line 174, in <module>
    mod = import_module(args.car_number)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import module  __import__(name)
  File "/home/tracerfire/src/CAR_2016_04_003.py", line 23
"to prevent the possibility of infection or further infection and investigate to determine if caused by crash or user manipulation. " \
SyntaxError:  unexpected character after line continuation character

**Comment by infosec-alchemist** [comment]
A "/" was at the end of the "CAR_DESCRIPTION" attribute.  It was removed
